# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GOOGLE_FB_SigniIn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GoogleSignIn'
  pod ‘FacebookLogin’
  pod ‘FacebookCore’

end
